version: '3'
services:
  postgres:
    image: postgres:11.1-alpine
    build:
      context: $WORK_DIR
      shm_size: '2gb'
    shm_size: '2gb'
    container_name: postgres
    environment:
      POSTGRES_DB: $DB_NAME
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASS
    ports:
      - 5432:5432
    volumes:
      - $WORK_DIR/data:/var/lib/postgresql/data
  app:
    container_name: app
    build:
      context: $WORK_DIR
      dockerfile: deploy/docker/app/Dockerfile
      args:
        APP: $APP
    env_file:
      - .env
    volumes:
      - $WORK_DIR:$APP
      - $STATIC_DIR:/static:z
    depends_on:
      - 'postgres'
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - $STATIC_DIR:/static:z
    depends_on:
      - app
volumes:
  pgdata: