version: '3'
services:
  app:
    container_name: app
    build:
      context: $WORK_DIR
      dockerfile: deploy/docker/app/Dockerfile
      args:
        APP: $APP
    env_file:
      - .env
    volumes:
      - $WORK_DIR:$APP
    networks:
      - nginx_network
  nginx:
    container_name: nginx
    image: nginx:1.21-alpine
    ports:
      - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on:
      - app
    networks:
      - nginx_network

networks:
  nginx_network:
    driver: bridge