# Generated by Django 3.1.1 on 2021-10-17 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField()),
                ('type', models.CharField(choices=[('Basic', 'Basic'), ('Gold', 'Gold'), ('Platinum', 'Platinum')], default='Basic', max_length=15)),
                ('balance', models.PositiveIntegerField(default=0)),
                ('max_transaction', models.PositiveIntegerField(default=500)),
                ('holder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card', to='config.student')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('for_bank', models.BooleanField(default=False)),
                ('for_shop', models.BooleanField(default=False)),
                ('for_attendance', models.BooleanField(default=False)),
                ('is_negative', models.BooleanField(default=False)),
                ('amount', models.PositiveIntegerField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='bank.card')),
            ],
        ),
    ]
