# Generated by Django 3.0.8 on 2020-07-31 22:00

from django.db import migrations, models
import django.db.models.deletion
import phone_field.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('graduation_year', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'alumni',
            },
        ),
        migrations.CreateModel(
            name='Bonus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WEEK', models.PositiveSmallIntegerField()),
                ('MONTH', models.PositiveSmallIntegerField()),
                ('QUARTER', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'attendance bonus',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BASIC', models.PositiveSmallIntegerField()),
                ('GOLD', models.PositiveSmallIntegerField()),
                ('PLATINUM', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'discount',
            },
        ),
        migrations.CreateModel(
            name='Servant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('middle_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('birth_day', models.DateField()),
                ('grade', models.PositiveSmallIntegerField(choices=[(9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11'), (12, 'Grade 12'), (13, 'Grade 13')])),
                ('school', models.CharField(max_length=50)),
                ('phone', phone_field.models.PhoneField(help_text='Contact phone number', max_length=31)),
                ('mothers_number', phone_field.models.PhoneField(help_text="Mother's contact phone number", max_length=31)),
                ('fathers_number', phone_field.models.PhoneField(help_text="Father's contact phone number", max_length=31)),
                ('father_of_confession', models.CharField(max_length=50)),
                ('residency_area', models.CharField(max_length=50)),
                ('servant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='config.Servant')),
            ],
        ),
    ]
